use_frameworks!
platform :ios, '10.0'


target 'Kitemetrics_Example' do
  pod 'Kitemetrics', :path => '../'
  pod 'SnapKit', '~> 5.0.0'

  target 'Kitemetrics_Tests' do
    inherit! :search_paths

    
  end
end
