use_frameworks!
platform :ios, '8.0'


target 'Kitemetrics_Example' do
  pod 'Kitemetrics', :path => '../'
  pod 'SnapKit', '4.0.0'

  target 'Kitemetrics_Tests' do
    inherit! :search_paths

    
  end
end
